/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.api.model.req;

import com.binance.connector.common.enums.*;
import lombok.Builder;
import lombok.Data;

/** NewOrderRequest */
@Data
@Builder
public class NewOrderRequest {

    private String symbol;

    private Side side;

    private OrderType type;

    private TimeInForce timeInForce;

    private Double quantity;

    private Double quoteOrderQty;

    private Double price;

    private String newClientOrderId;

    private Long strategyId;

    private Integer strategyType;

    private Double stopPrice;

    private Long trailingDelta;

    private Double icebergQty;

    private NewOrderRespType newOrderRespType;

    private SelfTradePreventionMode selfTradePreventionMode;

    private Long recvWindow;

}
