/*
 * Binance Derivatives Trading USDS Futures REST API
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.derivatives_trading_usds_futures.rest.api.model.req;

import com.binance.connector.common.enums.PositionSide;
import lombok.Data;

@Data
public class ModifyIsolatedPositionMarginRequest {

    /**
     * 交易对 必填
     */
    private String symbol;

    /**
     * 持仓方向，单向持仓模式下非必填，默认且仅可填BOTH;在双向持仓模式下必填,且仅可选择 LONG 或 SHORT
     */
    private PositionSide positionSide;

    /**
     * 保证金金额 必填
     */
    private Double amount;

    /**
     * 调整方向 1: 增加逐仓保证金，2: 减少逐仓保证金 必填
     */
    private String type;

}
