/*
 * Binance Derivatives Trading USDS Futures REST API
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.derivatives_trading_usds_futures.rest.api.model.req;

import com.binance.connector.common.enums.*;

/** NewOrderRequest */

public class NewOrderRequest {

    private String symbol;

    private Side side;

    private PositionSide positionSide;

    private String type;

    private TimeInForce timeInForce;

    private Double quantity;

    private String reduceOnly;

    private Double price;

    private String newClientOrderId;

    private Double stopPrice;

    private String closePosition;

    private Double activationPrice;

    private Double callbackRate;

    private WorkingType workingType;

    private String priceProtect;

    private NewOrderRespType newOrderRespType;

    private PriceMatch priceMatch;

    private SelfTradePreventionMode selfTradePreventionMode;

    private Long goodTillDate;

    private Long recvWindow;

    public NewOrderRequest() {}

}
