/*
 * Binance Derivatives Trading USDS Futures REST API
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.derivatives_trading_usds_futures.rest.api.model.resp;

import lombok.Data;

/**
 * 调整保证金返回西悉尼
 */
@Data
public class ModifyIsolatedPositionMarginResponse {

    private Double amount;

    private Long code;

    private String msg;

    private Long type;

}
