/*
 * Binance Derivatives Trading USDS Futures REST API
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.derivatives_trading_usds_futures.rest.api.model.resp;

import lombok.Data;

@Data
public class NewOrderResponse {

    private String clientOrderId;


    private String cumQty;


    private String cumQuote;


    private String executedQty;


    private Long orderId;


    private String avgPrice;

    private String origQty;

    private String price;

    private Boolean reduceOnly;

    private String side;

    private String positionSide;

    private String status;

    private String stopPrice;

    private Boolean closePosition;

    private String symbol;

    private String timeInForce;

    private String type;

    private String origType;

    private String activatePrice;

    private String priceRate;

    private Long updateTime;

    private String workingType;

    private Boolean priceProtect;

    private String priceMatch;

    private String selfTradePreventionMode;

}
