/*
 * Binance Derivatives Trading USDS Futures REST API
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.derivatives_trading_usds_futures.rest.api.model.resp;

import lombok.Data;

@Data
public class UserCommissionRateResponse {

    /**
     * 交易对
     */
    private String symbol;

    /**
     * 挂单手续费（限价买卖） 正常比较低
     */
    private String makerCommissionRate;

    /**
     * 吃单手续费（市价买卖）
     */
    private String takerCommissionRate;

}
