/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.api.model.resp;

public class CancelOrderResponse {

    private String symbol;


    private String origClientOrderId;


    private Long orderId;


    private Long orderListId;


    private String clientOrderId;

    private Long transactTime;

    private String price;

    private String origQty;

    private String executedQty;

    private String cummulativeQuoteQty;

    private String status;

    private String timeInForce;

    private String type;

    private String side;

    private String selfTradePreventionMode;

}
