/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.api.model.resp;

import lombok.Data;

import java.util.List;

@Data
/** DepthResponse */
public class DepthResponse {

    /**
     * 订单簿的最后更新 ID，表示该数据的版本或快照编号
     */
    private Long lastUpdateId;

    /**
     * 买盘 [价格-报价货币，挂单量-基础货币]
     */
    private List<List<String>> bids;

    /**
     * 卖盘 [价格-报价货币，挂单量-基础货币]
     */
    private List<List<String>> asks;


}
