/*
 * Binance Spot REST API
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.rest.api.model.resp;

import lombok.Data;

@Data
public class GetOrderResponse {

    /** 交易对 */
    private String symbol;

    /** 系统订单id */
    private Long orderId;

    /** */
    private Long orderListId;

    /** 客户订单id */
    private String clientOrderId;

    /** 订单价格 */
    private String price;

    /** 用户的原始订单数量 */
    private String origQty;

    /** 交易的订单数量 */
    private String executedQty;

    /** 累计的交易金额 */
    private String cummulativeQuoteQty;

    /** 订单状态 */
    private String status;

    /** 订单的时效方式 */
    private String timeInForce;

    /** 订单类型 如 市价 or 限价 */
    private String type;

    /** 订单方向 买 or 卖 */
    private String side;

    /** 止损价格 */
    private String stopPrice;

    /** 冰山数量 */
    private String icebergQty;

    /** 订单时间 */
    private Long time;

    /** 最后更新时间 */
    private Long updateTime;

    /** 订单是否出现在 orderbook中 */
    private Boolean isWorking;

    /** 订单添加到 orderbook的时间 */
    private Long workingTime;

    /** 原始交易金额 */
    private String origQuoteOrderQty;

    /** 如何处理自我交易模式 */
    private String selfTradePreventionMode;

}
